version: "3"

networks:
  fabric-iot:
    external:
      name: fabric-iot

services:
  ca_farm1:
    image: busan15/fabric-ca    
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-farm1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - /home/admin/Sample_Fabric_On_Rasp/test-network/organizations/fabric-ca/farm1:/etc/hyperledger/fabric-ca-server
    container_name: ca_farm1
    networks:
      fabric-iot:
        aliases:
          - ca.farm1.fabric-iot.com
