# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: "3"

volumes:
  peer0farm1fabriciot:

networks:
  fabric-iot:
    external:
      name: fabric-iot

services:
  peer0farm1fabriciot:
    deploy:
      placement:
        constraints:
          - node.labels.name == manager
    container_name: peer0.farm1.fabric-iot.com
    image: ottoflaherty/fabric-peer:arm64-2.3
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric-iot
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.farm1.fabric-iot.com
      - CORE_PEER_ADDRESS=peer0.farm1.fabric-iot.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.farm1.fabric-iot.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.farm1.fabric-iot.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.farm1.fabric-iot.com:7051
      - CORE_PEER_LOCALMSPID=farm1MSP
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0.fabric-iot.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - couchdb0
    volumes:
      - /var/run/:/host/var/run/
      - /home/admin/Sample_Fabric_On_Rasp/test-network/organizations/peerOrganizations/farm1.fabric-iot.com/peers/peer0.farm1.fabric-iot.com/msp:/etc/hyperledger/fabric/msp
      - /home/admin/Sample_Fabric_On_Rasp/test-network/organizations/peerOrganizations/farm1.fabric-iot.com/peers/peer0.farm1.fabric-iot.com/tls:/etc/hyperledger/fabric/tls
      - peer0farm1fabriciot:/var/hyperledger/production
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      fabric-iot:
        aliases:
          - peer0.farm1.fabric-iot.com
          
  couchdb0:
    container_name: couchdb0
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    networks:
      fabric-iot:
        aliases:
          - couchdb0.fabric-iot.com


  
